version: '2'
services:
  dockerapp:
    image: jleetutorial/dockerapp
    ports:
      - "5000:5000"
    # host directory : container directory
    volumes:
      - ./app:/app

  redis:
    image: redis:3.2.0